### ISSUE TITLE
Migrate to a WebExtension

### ISSUE THREAD

**Issue by mgol** [firephp/firephp.org#4]
Firefox will not support old-style XUL-based extensions starting November 2017 (in Firefox 57+). Do you have plans to migrate to a new WebExtension standard?

**Comment by cadorn** [comment]
Update: https://github.com/firephp/firephp-for-firefox-devtools/issues/1#issuecomment-319404934

I do hope to have a replacement before November.

**Comment by cadorn** [comment]
There is a first prototype available: https://github.com/firephp/firephp-for-firefox-devtools/issues/1#issuecomment-341957976
